#ifndef _SHADER_H_
#define _SHADER_H_

#include <cstdarg>

using std::va_list;

enum GLT_SHADER
{
	GLT_BASIC_SHADER = 0,
	GLT_COLOR_SHADER,
	GLT_TEXTURE_SHADER,
	GLT_LAMBERT_SHADER,
	GLT_PHONG_SHADER,
	GLT_COOK_TORRANCE_SHADER,
	GLT_OBJECT_2D_SHADER,
	GLT_DISSOLVE_SHADER,
	GLT_TOON_SHADER,
	GLT_SKYBOX_SHADER,
	GLT_BUMP_MAPPING_SHADER,
	GLT_LAMBERT_TEXTURE_SHADER,
	GLT_TERRAIN_SHADER,
	GLT_PARALLAX_MAPPING_SHADER,
	GLT_SHADOW_MAPPING_SHADER,
	GLT_GODRAYS_SHADER,
	GLT_VERTEX_VISUALIZER_SHADER,
	GLT_PARK_SHADER,
	GLT_LAMP_PARK_SHADER,
	GLT_DEPTH_SHADER,
	GLT_GROUND_PARK_SHADER,
	GLT_TESSELLATION_SHADER,
	GLT_SHADOW_BASIC_SHADER,
	GLT_FRAME_SHADER,
	GLT_COMPUTE_SHADER,
	GLT_ACCELERATION_SHADER,
	GLT_PARTICLE_SHADER
};

class Shader
{
public:
	virtual void SetShader() = 0;
	virtual void SetParameters(va_list) = 0;
	virtual void Shutdown() = 0;

};

#endif